// TODO: Please delete file after api integration

export const payrollData = [
  {
    id: 1,
    decription: "Monthly Salary for December ",
    paymentCyle: "Monthly",
    amount: "$17,949.28",
    dueDate: "Dec 28, 2022",
    paidOn: "Dec 28, 2022",
    status: "On-time",
  },
  {
    id: 2,
    decription: "Contractor Payout for Q4 Milestone",
    paymentCycle: "Weekly",
    amount: "$3625.75",
    paidOn: "Dec 15, 2022",
  },
  {
    id: 3,
    decription: "Monthly Salary for November",
    paymentCycle: "Monthly",
    amount: "$17,949.28",
    dueDate: "Nov 28, 2022",
    paidOn: "Nov 30, 2022",
    status: "Late",
  },
  {
    id: 4,
    decription: "Monthly Salary for October",
    paymentCycle: "Daily",
    amount: "$17,949.28",
    dueDate: "Oct 28, 2022",
    paidOn: "Oct 27, 2022",
    status: "Early",
  },
  {
    id: 5,
    decription: "Monthly Salary for September",
    paymentCycle: "Weekly",
    amount: "$15,200.00",
    dueDate: "Dec 28, 2022",
    paidOn: "Sep 28, 2022",
    status: "On Time",
  },
];

export const createPayrollData = [
  {
    id: 1,
    name: "Kelechi Iheanacho",
    avatarSrc: "",
    department: "Engineering",
    grossPay: 10000,
    commission: 5000,
    bonus: 100,
    deduction: 150,
    role: "Full Stack Developer",
    status: "Active",
  },
  {
    id: 2,
    name: "Alhassan Andrew",
    avatarSrc: "",
    department: "Engineering",
    grossPay: 200000,
    commission: 5000,
    bonus: 100,
    deduction: 150,
    role: "QA Engineer",
    status: "Active",
  },
  {
    id: 3,
    name: "Bernice Sviour ",
    avatarSrc: "",
    department: "Finance",
    grossPay: 50000,
    commission: 800,
    bonus: 100,
    deduction: 150,
    role: "Accountant",
    status: "Active",
  },
  {
    id: 4,
    name: "Robert James",
    avatarSrc: "",
    department: "Operations",
    grossPay: 60000,
    commission: 800,
    bonus: 100,
    deduction: 150,
    role: "Operations Officer",
    status: "Active",
  },
];
