-- CreateTable
CREATE TABLE "OTPs" (
    "id" TEXT NOT NULL,
    "otp" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,

    CONSTRAINT "OTPs_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "OTPs" ADD CONSTRAINT "OTPs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
