module.exports = {
    bracketSpacing: true,
    bracketSameLine: true,
    singleQuote: true,
    jsxSingleQuote: false,
    trailingComma: "es5",
    semi: true,
    printWidth: 110,
    arrowParens: "always",
    importOrder: [
        "^@(wyrecc|ee)/(.*)$",
        "^@components/(.*)$",
        "^@(server|trpc)/(.*)$",
        "^~/(.*)$",
        "^@/(.*)$",
        "^[./]",
    ],
    importOrderSeparation: true,
    plugins: [require("@trivago/prettier-plugin-sort-imports")],
};