name: Lint Workflow
on: push
jobs:
  lint:
    name: TS:ES Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
      - name: Set Yarn cache
        run: yarn config set cache-folder ~/.cache/yarn

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run Typescript Lint
        run: yarn lint:ts

      - name: Run EcmaScript Lint
        run: yarn lint:es
